# Generated by Django 5.0.4 on 2024-04-14 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_type',
            new_name='task_Status',
        ),
    ]
