# Generated by Django 5.0.4 on 2024-04-14 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_Status',
            new_name='task_type',
        ),
    ]
